name: Setup bendctl
description: setup bendctl for perf test
inputs:
  account_email:
    required: true
  account_password:
    required: true
  org:
    required: true

runs:
  using: composite
  steps:
    - name: Get bendctl from repo
      shell: bash
      run: |
        curl -fsSLo ./bendctl https://repo.databend.rs/tools/bendctl/amd64/bendctl
        chmod +x ./bendctl
        cp ./bendctl /usr/bin/bendctl

    - name: bendctl login
      shell: bash
        ./bendctl auth login --email=${{ inputs.email }} --password=${{ inputs.password }} --org=${{ inputs.org }}
