name: Reload data
description: reload test data for perf test
inputs:
  email:
    required: true
  password:
    required: true
  org:
    required: true
  script:
    required: true
  warehouse:
    required: true
  aws_key_id:
    required: true
  aws_secret_key:
    required: true
  feishu_webhook_url:
    required: true

runs:
  using: composite
  steps:
    - name: setup bendctl
      uses: ./.github/actions/setup-bendctl
      with:
        email: ${{ inputs.email }}
        password: ${{ inputs.password }}
        org: ${{ inputs.org }}

    - name: Ensure warehouse
      shell: bash
      run: |
        bendctl warehouse create ${{ inputs.warehouse }} --size=Small
      env:
        BENDCTL_API_ENDPOINT: https://test.datafusecloud.com

    - name: Run reload script
      shell: bash
      run: |
        bash -ex ${{ inputs.script }}
      env:
        AWS_KEY_ID: ${{ inputs.aws_key_id }}
        AWS_SECRET_KEY: ${{ inputs.aws_secret_key }}
        WAREHOUSE: ${{ inputs.warehouse }}
        BENDCTL_API_ENDPOINT: https://test.datafusecloud.com

