name: Perf

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '25 0 * * *'

jobs:
  perf:
    name: Databend Release Perf
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.REPO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_DEFAULT_OUTPUT: json

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Databend version
        id: databend_version
        run: |
          LASTEST_TAG=$(curl -s GET https://api.github.com/repos/datafuselabs/databend/tags\?per_page\=1 | jq -r '.[].name')
          echo ::set-output name=VERSION::${LASTEST_TAG}
      - name: Get Date
        id: perf_date
        run: |
          THE_DATE=$(date +"%Y-%m-%d")
          echo ::set-output name=DATE::${THE_DATE}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.REPO_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Get perf-tools from S3
        run: |
          aws s3 cp s3://databend-shared/tools/perf-tool/amd64/perf-tool perf-tool
      - name: Run Perf
        env:
          WEB_API_USER_EMAIL: ${{ secrets.WEB_API_USER_EMAIL }}
          WEB_API_USER_PASSWORD: ${{ secrets.WEB_API_USER_PASSWORD }}
          WAREHOUSE_TAG: ${{ steps.databend_version.outputs.VERSION }}
          WAREHOUSE_SIZE: ${{ secrets.WAREHOUSE_SIZE }}
        run: |
          chmod +x ./perf-tool
          ./perf-tool --output-format json --test-dir benchmarks -target-dir collector >> detail.log
          mv collector/numbers.json collector/numbers/${{ steps.perf_date.outputs.DATE }}-numbers.json
          mv collector/ontime.json collector/ontime/${{ steps.perf_date.outputs.DATE }}-ontime.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'perf: collect performance data from the latest release'
      - name: Setup Go Env
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Print Go Version
        run: go version
      - name: Do Transform
        run: go run script/transform.go >> detail.log
      - name: Upload Result
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: temp
          destination_dir: json
          keep_files: false
          commit_message: 'Update Transform Data'

      - name: Make summary log
        run: |
          head -10 detail.log 
          tail -30 detail.log > summary.log
      - name: Read lastest log
        if: ${{ failure() }}
        uses: juliangruber/read-file-action@v1
        with:
          path: summary.log
      - name: Nofity By Email
        uses: dawidd6/action-send-mail@v3
        if: ${{ failure() }}
        with:
          server_address: smtp.feishu.cn
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Databend Perf Github Actions job result
          to: xuzhiqing2014@outlook.com, xuzhiqing2014@163.com
          from: databend-perf
          secure: true
          body: "Build job of ${{github.repository}} run failed, lastest output: \n${{ steps.package.outputs.content }}\n For detail log, see attachment file."
          attachments: detail.log
