name: Reload

on:
  pull_request:
    branches:
      - main
    paths:
      - "reload/**"
      - ".github/workflows/reload.yaml"
  push:
    branches:
      - main
    paths:
      - "reload/**"
      - ".github/workflows/reload.yaml"
  schedule:
    # Runs at 08:25 UTC on Fri.
    - cron: '25 8 * * 5'

jobs:
  perf:
    name: Perf Data Reload
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get perf-tools from repo
        run: |
          curl -fsSLo script/perf-tool https://repo.databend.rs/tools/perf-tool/amd64/perf-tool-2022-07-11-48525b9
          chmod +x ./script/perf-tool

      - name: Reload hits
        env:
          WEB_API_USER_EMAIL: ${{ secrets.WEB_API_USER_EMAIL }}
          WEB_API_USER_PASSWORD: ${{ secrets.WEB_API_USER_PASSWORD }}
          WAREHOUSE_SIZE: ${{ secrets.WAREHOUSE_SIZE }}
          AWS_KEY_ID: ${{ secrets.REPO_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
        run: |
          ./script/perf-tool --output-format json --test-dir reload/hits -target-dir collector/hits-reload -test-time 1 -warm-time 0
          mv collector/hits-reload/reload_hits.json collector/hits-reload/${{ steps.perf_date.outputs.DATE }}-reload-hits.json
          git diff

      - name: Reload ontime
        env:
          WEB_API_USER_EMAIL: ${{ secrets.WEB_API_USER_EMAIL }}
          WEB_API_USER_PASSWORD: ${{ secrets.WEB_API_USER_PASSWORD }}
          WAREHOUSE_SIZE: ${{ secrets.WAREHOUSE_SIZE }}
          AWS_KEY_ID: ${{ secrets.REPO_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
        run: |
          ./script/perf-tool --output-format json --test-dir reload/ontime -target-dir collector/ontime-reload -test-time 1 -warm-time 0
          mv collector/ontime-reload/reload_ontime.json collector/ontime-reload/${{ steps.perf_date.outputs.DATE }}-reload-ontime.json
          git diff

      - name: Notify Feishu Group
        uses: foxundermoon/feishu-action@v2
        if: ${{ always() }}
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: Reload job of ${{ github.repository }} run ${{ job.status }}
                content:
                - [{"tag": "a", "text": "link", "href": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]
