name: Reload

on:
  pull_request:
    branches:
      - main
    paths:
      - "reload/**"
      - ".github/workflows/reload.yaml"
  push:
    branches:
      - main
    paths:
      - "reload/**"
      - ".github/workflows/reload.yaml"
  schedule:
    # Runs at 08:25 UTC on Fri.
    - cron: '25 8 * * 5'

jobs:
  reload-hits:
    name: Reload data: hits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: setup bendctl
        uses: ./.github/actions/setup-bendctl
        with:
          account_email: ${{ secrets.WEB_API_USER_EMAIL }}
          account_password: ${{ secrets.WEB_API_USER_PASSWORD }}
          org: orgchasen-slug-test

      - name: Reload
        uses: ./.github/actions/reload
        with:
          script: ./reload/hits.sh
          warehouse: reload
