name: Reload workflow

on:
  workflow_call:
    inputs:
      script:
        required: true
        type: string

jobs:
  reload:
    name: Reload
    runs-on: [self-hosted, X64, Linux, development]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Reload
        uses: ./.github/actions/reload
        with:
          email: ${{ secrets.WEB_API_USER_EMAIL }}
          password: ${{ secrets.WEB_API_USER_PASSWORD }}
          org: orgchasen-slug-test
          script: ${{ inputs.script }}
          warehouse: reload
          aws_key_id: ${{ secrets.REPO_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
          feishu_webhook_url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
